FROM node:18-alpine as build

WORKDIR /app

COPY package.json ./
RUN npm install

COPY . ./

RUN npm run build

FROM node:16-alpine

WORKDIR /app

COPY --from=build /app/.output ./.output/
COPY --from=build /app/.nuxt ./.nuxt/

EXPOSE 3000
CMD [ "node", ".output/server/index.mjs" ]
