version: '3'

volumes:
  production_postgres_data: {}

services:
  backend:
    image: mystrapi:latest
    container_name: production_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    depends_on:
      - postgres    
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/public/uploads:/opt/app/public/uploads
    restart: always
    env_file: .env    
    ports:
      - '1337:1337'

  frontend:
    container_name: production_frontend
    build:  
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    environment: 
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true

  nginx:
    container_name: nginx
    build:  
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    restart: always
    env_file: .env   
    ports:
      - '8080:8080'

  postgres:
    image: postgres:14.5-alpine
    container_name: production_db
    platform: linux/amd64 #for platform error on Apple M1 chips
    volumes:
      - production_postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
      