version: '3'

volumes:
  template_data: {}

services:
  backend:
    image: mystrapi:latest
    container_name: local_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/.env:/opt/app/.env
      - ./backend/public/uploads:/opt/app/public/uploads
    restart: always
    env_file: .env
    ports:
      - '1337:1337'

  frontend:
    container_name: local_frontend
    build:  
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/nginx:/etc/nginx/conf.d
    restart: always
    env_file: .env
    ports:
      - 8080:8080
    environment: 
      - CHOKIDAR_USEPOLLING=true

  postgres:
    image: postgres:14.5-alpine
    container_name: local_db
    platform: linux/amd64 #for platform error on Apple M1 chips
    volumes:
      - template_data:/var/lib/postgresql/data/
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
      